services:
  kavita:
    image: jvmilazz0/kavita:latest
    volumes:
      - kavita-manga:/manga
      - kavita-comics:/comics
      - kavita-books:/books
      - kavita-config:/kavita/config
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "5000:5000"
    restart: unless-stopped
