services:
  kavita:
    image: jvmilazz0/kavita:latest
    volumes:
      - /mnt/elements/pub/biblio/manga:/manga
      - /mnt/elements/pub/biblio/comics:/comics
      - /mnt/elements/pub/biblio/books:/books
      - kavita-config:/kavita/config
    environment:
      - PUID=1000
      - PGID=1007
      - TZ=America/Sao_Paulo
    ports:
      - "5000:5000"
    restart: unless-stopped
