services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    restart: unless-stopped
    environment:
      - SB_USER=${SB_USER}
      - SB_INDEX_PAGE=Home
      - SB_AUTH_TOKEN=${SB_AUTH_TOKEN}
    volumes:
      - sb_data:/space
    ports:
      - 3000:3000
  # To enable auto upgrades, run watchtower
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
